# Ref https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - alertmanager.sandbox.sneto.ca
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - grafana.sandbox.sneto.ca
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - prometheus.sandbox.sneto.ca
